In [ ]:
from typing_extensions import final
import sklearn
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from numpy import convolve
import matplotlib.pyplot as plt
import math
from sklearn import metrics
from scipy.stats import kurtosis
from scipy.stats import skew
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
from sklearn import neighbors, datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import statistics

import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import ConfusionMatrixDisplay

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
data = np.loadtxt('/content/gdrive/MyDrive/AI_Hust_VLC /Du_lieu_gia_toc/datachuan/local_global_all/unnormal_feature_n8.csv', delimiter = ',')
X_raw = data[:,:-1]

#normalized du lieu ve mien [0;1]

# tạo bộ scaler
scaler =  MinMaxScaler() 
#fit scaler vao X_raw và thực hiện scale
X = scaler.fit_transform(X_raw)

y = data[:,-1]

In [ ]:
print(len(X[1]))

576


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=200)

In [ ]:
#svm
# khởi tạo SVM classifier
clf = svm.SVC(kernel='linear') 
# Train classifier với dữ liệu
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

hs_svm = metrics.accuracy_score(y_test, y_pred)
print (round(100* hs_svm,2))

96.01


In [ ]:
def classifer (X , y, class_method = 'SVM', k = 2, h = 100, c = 11, g = 0.9875, kn = 'linear'):
    hs = []
    kf = KFold(n_splits=4)
    kf.get_n_splits(X)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        if class_method == 'SVM' :
            clf = svm.SVC(C = c, kernel = kn, gamma = g) 
            clf.fit(X_train, y_train)
            y_pred = clf.predict(X_test)

            hs_svm = metrics.accuracy_score(y_test, y_pred)
            hs.append(round(100* hs_svm,1))
            cnf_matrix = confusion_matrix(y_test, y_pred)
            


        if class_method == 'KNN' :
            knn = KNeighborsClassifier(n_neighbors = k)
            knn.fit(X_train,y_train)
            y_pred = knn.predict(X_test)
            
            hs_knn = metrics.accuracy_score(y_test, y_pred)
            hs.append(round(100* hs_knn,1))
            cnf_matrix = confusion_matrix(y_test, y_pred)

        
        if class_method == 'RF' :
            rf = RandomForestClassifier(n_estimators = h)
            rf.fit(X_train, y_train)
            y_pred = rf.predict(X_test)

            hs_rf = metrics.accuracy_score(y_test, y_pred)        
            hs.append(round(100* hs_rf,1))
            cnf_matrix = confusion_matrix(y_test, y_pred)
      
    return hs, cnf_matrix

m, c = classifer(X, y, class_method = 'SVM',c = 1,g = 1/576)
print("Do chinh xac qua 4 lan danh gia: ")
print(m)
print("Ma tran nham lan: ")
print(c)

Do chinh xac qua 4 lan danh gia: 
[92.6, 90.8, 92.6, 86.0]
Ma tran nham lan: 
[[80  0  0  0  0  0 13  1  0  0  0  0]
 [ 1 89  0  0  0  0  0  0  0  0  2  2]
 [ 2  0 70  0  0  1  0  0  1  0  1 19]
 [ 3  0  0 78  0  0  2  0  0  1  8  2]
 [ 1  0  0  0 86  4  3  0  0  0  0  0]
 [ 1  0  0  0  0 90  0  0  0  0  3  0]
 [ 6  0  0  0  1  0 77  1  0  0  0  9]
 [24  0  0  0  0  0  0 70  0  0  0  0]
 [ 2  2  3  1  0  3  0  0 78  0  1  4]
 [ 1  0  0  4  0  2  0  0  0 82  5  0]
 [ 8  0  0  0  0  1  1  6  0  0 78  0]
 [ 1  0  1  0  0  0  0  0  0  0  0 92]]
